import { defineSlotRecipe } from '@pandacss/dev'
export const cartLineItem = defineSlotRecipe({
  className: 'cartLineItem',
  slots: [
    'root',
    'container',
    'content',
    'image',
    'info-column',
    'details',
    'product-name',
    'product-id',
    'variations',
    'promotions',
    'controls-column',
    'stock-status',
    'quantity-control',
    'price-column',
    'remove-button',
    'price-display',
    'availability-alert',
  ],
  base: {
    root: {
      display: 'flex',
      flexDirection: 'column',
    },
    container: {
      display: 'flex',
      flexDirection: 'column',
      gap: '0',
      alignItems: 'stretch',
      containerType: 'inline-size',
    },
    content: {
      display: 'flex',
      gap: '4',
      w: 'full',
      pr: { mdDown: 5 },
      justifyContent: 'space-between',
      position: 'relative',
      pb: '4',
    },
    image: {
      aspectRatio: '1/1',
      width: { base: '80px', '@/xl': '120px' },
      height: { base: '80px', '@/xl': '120px' },
      '& img': { borderRadius: 'sm' },
    },
    'info-column': {
      display: 'flex',
      gap: '4',
      flexDirection: { base: 'column', md: 'row' },
      flex: '1',
    },
    details: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'flex-start!',
      width: { base: 'full', md: '235px' },
    },
    'product-name': {
      fontSize: 'sm',
      fontWeight: '500',
      color: 'text.strong',
      mb: '1',
    },
    'product-id': {
      fontSize: 'xs',
      color: 'text.subtle',
      mb: '1',
    },
    variations: {
      display: 'flex',
      flexDirection: 'column',
      gap: '1!',
      mb: '1',
    },
    'controls-column': {
      display: 'flex',
      flexDirection: 'column',
      width: 'full',
      gap: '3',
      alignItems: 'flex-start!',
      flex: '1',
    },
    'stock-status': {
      display: 'flex',
      flexDirection: 'column',
      gap: '0',
      alignItems: 'flex-start',
    },
    'quantity-control': {
      maxWidth: '140px',
    },
    'price-column': {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-between',
      height: 'full',
      alignItems: 'flex-end!',
      flex: '2',
    },
    'remove-button': {
      mdDown: {
        position: 'absolute',
        top: '4',
        right: '5px',
      },
    },
    'price-display': {
      textAlign: 'right',
      textStyle: 'static14',
      mdDown: {
        position: 'absolute',
        bottom: 0,
        left: { base: '100px', sm: '138px' },
      },
    },
    'availability-alert': {
      marginBottom: '1',
      width: 'full',
    },
  },
})
