import { defineSlotRecipe } from '@pandacss/dev'

export const orderSummary = defineSlotRecipe({
  className: 'orderSummary',
  slots: [
    'root',
    'checkout-button',
    'ledger',
    'ledger-item',
    'heading',
    'coupon-code',
    'total',
    'subtotal',
    'discount',
    'shipping',
    'tax',
    'donation',
    'gift-card',
    'order-total',
    'order-discount',
    'shipping-discount',
    'tax-discount',
  ],
  base: {
    root: {
      p: '5',
      gap: '5',
      height: 'fit-content',
      border: '1px solid token(colors.border.weak)',
      borderRadius: 'md',
      gridColumn: { base: 'span 2', sm: 'span 1' },
      bg: 'white',
      display: 'flex',
      flexDirection: 'column',
    },
    'checkout-button': {
      position: { base: 'fixed', md: 'initial' },
      bottom: '0',
      left: '0',
      right: '0',
      px: { base: '4', md: '0' },
      py: { base: '2', md: '0' },
      zIndex: 'docked',
      backgroundColor: 'white',
      borderTop: { base: '1px solid token(colors.border.weak)', md: 'none' },
      mt: { base: '0', md: '2' },
    },
    ledger: {
      display: 'flex',
      flexDirection: 'column',
      gap: '4',
    },
  },
})
